"""fixed enum in user model

Revision ID: 90b69de27e6a
Revises: a4c056dd5fb3
Create Date: 2025-12-01 16:46:19.439527

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "90b69de27e6a"
down_revision: Union[str, Sequence[str], None] = "a4c056dd5fb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "tarifplan",
        existing_type=postgresql.ENUM("base", "premium", name="usertarifplan"),
        type_=sa.String(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'base'::usertarifplan"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "tarifplan",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM("base", "premium", name="usertarifplan"),
        existing_nullable=False,
        existing_server_default=sa.text("'base'::usertarifplan"),
    )
    # ### end Alembic commands ###
