"""empty message

Revision ID: e197c6441ed0
Revises: 90b69de27e6a
Create Date: 2025-12-03 18:49:48.285333

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e197c6441ed0"
down_revision: Union[str, Sequence[str], None] = "90b69de27e6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("links", sa.Column("click_counter", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("links", "click_counter")
    # ### end Alembic commands ###
