"""added ip for click

Revision ID: 5427dd32188e
Revises: e197c6441ed0
Create Date: 2025-12-04 17:39:18.332473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5427dd32188e"
down_revision: Union[str, Sequence[str], None] = "e197c6441ed0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clicks", sa.Column("user_ip", sa.Integer(), nullable=False))
    op.drop_column("clicks", "region")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clicks", sa.Column("region", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("clicks", "user_ip")
    # ### end Alembic commands ###
