"""empty message

Revision ID: 59996193a7b2
Revises: 4e08a5a34934
Create Date: 2025-11-26 17:27:41.058198

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59996193a7b2"
down_revision: Union[str, Sequence[str], None] = "4e08a5a34934"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("link", sa.Column("base_url", sa.String(), nullable=False))
    op.create_unique_constraint(None, "link", ["url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "link", type_="unique") #type: ignore
    op.drop_column("link", "base_url")
    # ### end Alembic commands ###
